### ISSUE TITLE
Persist data from model to mongodb

### ISSUE THREAD

**Issue by fuqcool** [ahchoo/realtime#11]

**Comment by dafeizizhu** [comment]
node mongoose module can do this job... just need a mongodb server :)

**Comment by fuqcool** [comment]
Yeah, we just want some one to explore this thing. @dafeizizhu

**Comment by fuqcool** [comment]
Now we can connect to real mongodb. This can be closed.
see commit: 79b04c194b0dba54a9fd455a9ea3b543c53fa63a
