### ISSUE TITLE
qrcode

### ISSUE THREAD

**Issue by fuqcool** [ahchoo/realtime#114]

**Comment by BohanHsu** [comment]
I'm little hesitate about that. As for this idea is for quick add test player to game. We should figure out a way to clean those one time account.

**Comment by BohanHsu** [comment]
My mind changed a little about this about qrcode:
1. in manage/game page, there should be a qrcode related to this game.
2. user scan this page lead to our user portal
3. login user will be redirect to game room page, waiting to start the game.
4. not login user will be redirect to login page, login then redirect to game room.
5. not registered user could open signup page, registered and then being redirected to game page.

not 100% sure this is  implementable right now, and I will put this issue at the bottom of the priority queue. 
I abandoned the idea that let unregistered user simple put in a name and goes to game room. That is not good for us to collect game records.

**Comment by fuqcool** [comment]
Done.
