### ISSUE TITLE
About directory structure

### ISSUE THREAD

**Issue by fuqcool** [ahchoo/realtime#14]
Here is the changes I am thinking
- server.js    // script to bootstrap the server, should be a tiny file
- lib/             // source code
  - models/
    ...
  - routes/
  - others/
- demo/        // demo site
- public/        // website

We can serve both demo/ and public/, in different paths, which is cool.

I need your comment :)
@dafeizizhu @BohanHsu

**Comment by dafeizizhu** [comment]
I still doubt about the directory 'lib'... why use this name? should 'lib' refer to the third party code?

**Comment by fuqcool** [comment]
I was also wondering.
But it seems to be the convention of npm packages.

**Comment by BohanHsu** [comment]
lib is a little bit confusing, in rails it called app

**Comment by fuqcool** [comment]
I am fine with either.

Alright let's use app/ instead

@dafeizizhu Is it good to you?

**Comment by dafeizizhu** [comment]
OK.

**Comment by fuqcool** [comment]
Let's just follow up the convention :)

**Comment by fuqcool** [comment]
@dafeizizhu Can you try to implement this?
1. move routes into lib/routes
2. serve demo site together with /public

**Comment by dafeizizhu** [comment]
1. already moved into lib
2. see https://github.com/ahchoo/realtime/pull/24

**Comment by fuqcool** [comment]
Not so fancy.

I think we can
- ~~move all demo routes to lib/routes/demo~~
- ~~move socket io code to lib/socket.js~~

Done in commit 8e9f5e6514e9d5b1eb328023e6d165ea151a09d4

@dafeizizhu

**Comment by dafeizizhu** [comment]
`gulp initdb`

I can not find this one until i find the 'fixture' string through my working directory...

**Comment by fuqcool** [comment]
I think this is done.
