### ISSUE TITLE
About linting and formatting...

### ISSUE THREAD

**Issue by dafeizizhu** [ahchoo/realtime#2]
This issue is about the specific rules of js linter.

This is [some rules](http://www.jshint.com/docs/options/) about linting, maybe we should use some of them to lint our js code.

What about formatting? Should we use some plugin or just make some rules orally?

@fuqcool

**Comment by fuqcool** [comment]
I don't want limit too much the way we can write javascript. And I believe in our code quality. :-)

But I do want to have some rules to prevent us making stupid mistakes, such as "variable defined but not used", "defined a variable without _var_"

What do you think?

**Comment by fuqcool** [comment]
Done.

**Comment by dafeizizhu** [comment]
nice.
