### ISSUE TITLE
Explore server side testing

### ISSUE THREAD

**Issue by fuqcool** [ahchoo/realtime#43]

**Comment by dafeizizhu** [comment]
in progress, see the code on branch 'testing'.

**Comment by dafeizizhu** [comment]
see https://github.com/ahchoo/realtime/commit/473996066206e0db76af17e092f0d876bee67004

I use some mock to test without mongodb server. Here is a game router testcase example:

```
  it('POST /api/games', function (done) {
    request(app)
      .post('/api/games')
      .type('form')
      .send({ name: 'tj' })
      .set('Accept', 'application/json')
      .end(function (err, res) {
        expect(err).to.be.not.ok
        expect(gameModel.create).have.been.calledWith({ name: 'tj' })
        done()
      })
  })
```

**Comment by fuqcool** [comment]
We don't necessarily need to test for function call. We can just check the response from a outsider's perspective.

**Comment by fuqcool** [comment]
For example, we init db with data A, and we send a request, and then we expect the db to have data B.

**Comment by dafeizizhu** [comment]
got it. see the code on branch https://github.com/ahchoo/realtime/tree/test-use-mongodb

**Comment by fuqcool** [comment]
@dafeizizhu That's fantastic!
It will be even better if we use an in-memory database. And initialize it to whatever state in each of the test cases.

**Comment by dafeizizhu** [comment]
found a module to do this: [mockgoose](https://www.npmjs.org/package/mockgoose)

see this commit: https://github.com/ahchoo/realtime/commit/71df8dcca6465bff5ea75b89c51bf8422ed99c8d

@fuqcool

**Comment by fuqcool** [comment]
@dafeizizhu That looks great!

Can you do some demo testing on game api, and try to remove the `setTimeout` as well ?

**Comment by dafeizizhu** [comment]
1. game api means crud for game? see https://github.com/ahchoo/realtime/commit/f0456e3e04bcf87d59581a6d52588c98f4d253f9
2. I add some callback in `fixture/index.js` so we can know when the db is inited, then we can remove all `setTimeout`. see https://github.com/ahchoo/realtime/commit/8691eb7e842ace31e4636d58327463938aac764f

@fuqcool

**Comment by fuqcool** [comment]
Seems good! Can you send a pull request, and integrate with travis CI?
In this case we can set `npm test` using `gulp test` in package.json

Thanks a lot! @dafeizizhu

**Comment by dafeizizhu** [comment]
pr see https://github.com/ahchoo/realtime/pull/45, including script `npm test`.

**Comment by fuqcool** [comment]
merged.

**Comment by fuqcool** [comment]
This ticket can be closed.
