### ISSUE TITLE
Record each time of user clicking

### ISSUE THREAD

**Issue by fuqcool** [ahchoo/realtime#51]

**Comment by BohanHsu** [comment]
Did we introduced Game Room concept in socket/game.js? From my understanding server is broadcasting to every one listen to this port?

**Comment by BohanHsu** [comment]
Where did we call the function defined in socket/game.js?
@fuqcool

**Comment by BohanHsu** [comment]
Ok, I find where we used that.

**Comment by dafeizizhu** [comment]
@BohanHsu 

I do not use the room of socket.io. I attach the gameId to the event, like:

```
socket.broadcast.emit('game:start:' + gameId)
```

use this way to simulate a 'room' includes all users in a game.

**Comment by fuqcool** [comment]
Both works. I think it makes more sense to send events within room. This is how we designed data structure.

Note: broadcast sends event to everybody that is connected right now, except current connection/socket.

**Comment by dafeizizhu** [comment]
Because I don't really know how the 'room' exactly work, so I use the basic usage above...
