### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by BohanHsu** [ahchoo/realtime#53]
currently our models missing validation. Probably need to discuss what should be validate first.

**Comment by dafeizizhu** [comment]
there are some problem with validation now. Should we validate the input fields in the models or in the routers? If we do the validation in the routers, we need to write code to validate input fields in the routers with the same model ( such as `/lib/routes/user` and `/lib/routes/manage/users`) ...

@fuqcool any ideas about this problem?

**Comment by fuqcool** [comment]
Let's not validate input fields for now.

Validating by route should be enough.
