### ISSUE TITLE
access control

### ISSUE THREAD

**Issue by BohanHsu** [ahchoo/realtime#55]
For our current system, we have the following user role
1. Admin (administrator)
2. Player (a guy register and playing the game)
3. Guest (someone hanging around our website without sign in)

Access control is at controller level(not sure controller is the right word in expressJS's dictionary.). It is at the bottom of middleware. 
Example will be add when I get things work.

**Comment by fuqcool** [comment]
@dafeizizhu Can you explain the models added?

**Comment by dafeizizhu** [comment]
still thinking, wait for the complete implementation.

**Comment by fuqcool** [comment]
I think we need to consider carefully whether we need a complicated access control thing.
@dafeizizhu

**Comment by dafeizizhu** [comment]
it is not so complicate, the first version just store the permission information in mongo. just need a few code.

**Comment by dafeizizhu** [comment]
see the file https://github.com/ahchoo/realtime/blob/api-permission/lib/middlewares/permission.js

i also do some db initialization to generate the dynamic access control data models:
1. `/lib/models/role`.
2. `/lib/models/privilege`, means some action along with url and method, such as '/api/auth' and 'post'.
3. `/lib/models/user-in-role` and `/lib/models/privilege-in-role`, the many-many relationship between these models.

u can add some params to permission middleware, as the usage before i modify, it is hard coded premission. if u ignore the params, it will look up the permission information through mongodb.

@fuqcool @BohanHsu if u want simple, just use this middleware as the one @BohanHsu created.

i also doing the management background that i can modify all infomation, such as users, items, and permission infomation through a web page.

~~and now there are some issues about testing, the next commit will ignore permission checking when testing.~~

**Comment by fuqcool** [comment]
That's fucking awesome!
Can you please do an demo configuration? so we know how to use it.

@dafeizizhu Appreciated!

**Comment by dafeizizhu** [comment]
i will make the complete management in this week.

**Comment by fuqcool** [comment]
Sounds good.
