### ISSUE TITLE
Make test case more succinct using deep equal expect

### ISSUE THREAD

**Issue by fuqcool** [ahchoo/realtime#58]
I think it's better to expect(a).to.equal(b) , rather than doing expect for each property.

Do you agree with me ?
@dafeizizhu

**Comment by dafeizizhu** [comment]
I prefer doing expect for each properties. The 'id' property is different between each testing. It is hard to do the assertion you mention above.

**Comment by fuqcool** [comment]
Or we can make a deep match

**Comment by fuqcool** [comment]
The only problem is readability, it cost me a lot of time trying to understand what the tests is doing.

**Comment by dafeizizhu** [comment]
I do not konw what you mean about readability. Maybe you can make some modification on the code ifself or discuss this issue with me using IM (like QQ).

**Comment by fuqcool** [comment]
OK, I will create a pull request once it's ready.

**Comment by fuqcool** [comment]
All right, let's close it now. We can always revisit it in the future.

@dafeizizhu
