### ISSUE TITLE
http to https

### ISSUE THREAD

**Issue by fuqcool** [ahchoo/realtime#59]

**Comment by dafeizizhu** [comment]
I do not know how to do this on openshift... please help @fuqcool 

http://cloudhostingsource.com/setup-ssl-certificate-openshift/

Orz

**Comment by dafeizizhu** [comment]
I make a demo, but I don't know if it works on production...

code on https://github.com/ahchoo/realtime/tree/ssl-server

**Comment by fuqcool** [comment]
In order to use your own SSL certificate, you first need to upgrade your Openshift account to the “Silver Plan”

**Comment by fuqcool** [comment]
Let's shelf it.
